### ISSUE TITLE
About image processing

### ISSUE THREAD

**Issue by DRAEYE** [truecarfield/Automatic-Landing-Control-of-a-Quadrotor-UAV#1]
Excuse me, when I try to run this code, I can't find the image processing part in the whole project, I wonder how do you get the position information of the car on the ground? Maybe I haven't got through it clearly?

**Comment by truecarfield** [comment]
Hi

Sorry this one doesn’t have image processing part, the position is directly got from the robot odometry.

Here in https://github.com/truecarfield/tud_firefly_landing_sim is another implementation based on another simulator „rotors_simulaton“. There beside the robot odometry, the relative position between UAV and UGV is also acquired with mono camera and arucal marker using ROS package ar_sys.

Best regards



Am 21.11.2018 um 12:55 schrieb DRAEYE <notifications@github.com<mailto:notifications@github.com>>:


Excuse me, when I try to run this code, I can't find the image processing part in the whole project, I wonder how do you get the position information of the car on the ground? Maybe I haven't got through it clearly?

**Comment by DRAEYE** [comment]
Thanks a lot!
